// GENERATED BY TRAILBLAZE DAEMON. DO NOT EDIT.
// Re-runs on daemon restart. Idempotent — content-stable across restarts of the same toolset.
// Safe to commit (treat as API contract) OR gitignore (treat as derived output).

declare module "@trailblaze/scripting" {
  interface TrailblazeToolMap {
    /**
     * Force-stops the Google Clock app and re-launches it via the package's default
     * launcher activity, so the next step starts from a clean app state. Equivalent to a
     * Maestro `launchApp({ launchMode: FORCE_RESTART })` against `com.google.android.deskclock`,
     * but composed entirely from the dual-mode `android_adbShell` primitive so the same tool
     * works on host- and on-device-dispatched scripted-tool sessions.
     * 
     * Use this as the first step of any clock trail that wants a fresh launch state. No
     * arguments — the framework resolves the app id from the `clock` trailmap manifest's
     * `app_ids:` list against installed apps on the connected device.
     * 
     */
    clock_android_launchApp: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Wipes all alarms, timers, and stopwatch state from the Google Clock app via
     * `pm clear` followed by `am force-stop`, so the next launch starts from a fresh
     * data directory. Useful as a setup primitive for trails that need a known-clean
     * Clock state without the side effect of leaving the app open.
     * 
     * No arguments — the framework resolves the app id from the `clock` trailmap manifest's
     * `app_ids:` list against installed apps on the connected device. Composes only the
     * dual-mode `android_adbShell` primitive, so this tool works on both host- and on-device-
     * dispatched sessions.
     * 
     */
    clock_clearAlarms: {
      args: Record<string, never>;
      result: string;
    };
  }
}

export {};
