// GENERATED BY TRAILBLAZE DAEMON. DO NOT EDIT.
// Re-runs on daemon restart. Idempotent — content-stable across restarts of the same toolset.
// Safe to commit (treat as API contract) OR gitignore (treat as derived output).

declare module "@trailblaze/scripting" {
  interface TrailblazeToolMap {
    /**
     * Force-stops the Google Contacts app and re-launches it via the package's default
     * launcher activity, so the next step starts from a clean app state. Equivalent to a
     * Maestro `launchApp({ launchMode: FORCE_RESTART })` against `com.google.android.contacts`,
     * but composed entirely from the dual-mode `android_adbShell` primitive so the same tool
     * works on host- and on-device-dispatched scripted-tool sessions.
     * 
     * Use this as the first step of any contacts trail that wants a fresh launch state. No
     * arguments — the framework resolves the app id from the `contacts` trailmap manifest's
     * `app_ids:` list against installed apps on the connected device.
     * 
     */
    contacts_android_launchApp: {
      args: Record<string, never>;
      result: string;
    };
  }
}

export {};
