id: droidcon_android_settingsToAboutApp
description: Open the About App page from the Settings list.
shortcut:
  from: droidcon/android/event-settings
  to: droidcon/android/event-about-app
parameters: []
tools:
  - tapOnElementBySelector:
      reason: Open About App
      nodeSelector:
        androidAccessibility:
          contentDescriptionRegex: "About App"
