// GENERATED BY TRAILBLAZE DAEMON. DO NOT EDIT.
// Re-runs on daemon restart. Idempotent — content-stable across restarts of the same toolset.
// Safe to commit (treat as API contract) OR gitignore (treat as derived output).

declare module "@trailblaze/scripting" {
  interface TrailblazeToolMap {
    /**
     * Force-stops Google Calendar and re-launches it via the package's default launcher
     * activity, so the next step starts from a clean app state. Composed from the dual-mode
     * `android_adbShell` primitive so the same tool works on host- and on-device-dispatched
     * scripted-tool sessions. No arguments — the framework resolves the app id from the
     * `calendar` trailmap manifest's `app_ids:` list against installed apps on the device.
     * 
     */
    calendar_android_launchApp: {
      args: Record<string, never>;
      result: string;
    };
  }
}

export {};
